
services:

  video_hosting:
    build: ./project_video_hosting
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]

    volumes:
      - ./project_video_hosting:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
    env_file:
      - ./project_video_hosting/.env
    depends_on:
      - my-postgres


  web: 
    build: ./project_jwt
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./project_jwt:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    env_file:
      - ./project_jwt/.env

      
  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file:
      - ./project_jwt/.env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet myminio/photos;
      /usr/bin/mc policy set none myminio/photos;

      /usr/bin/mc mb --quiet myminio/videos;
      /usr/bin/mc policy set none myminio/videos;
      "

  my-postgres:
    image: postgres:17.4-alpine3.21
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./project_jwt/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
  celery:
    build: ./project_jwt/
    command: celery -A project_jwt worker -l info
    volumes:
      - ./project_jwt/:/redis
    depends_on:
      - redis

  celery-beat:
    build: ./project_jwt/
    command: celery -A project_jwt beat -l info
    volumes:
      - ./project_jwt/:/celery
    depends_on:
      - redis

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
    - 8888:8888
    volumes:
      - ./project_jwt/:/flower_data
  
  rabbit:
    image: rabbitmq:4-management
    hostname: localhost
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - ./project_jwt/:/rabbit
    depends_on:
      - video_hosting_listener

  video_hosting_listener:
    image: jwttask-video_hosting:latest
    command: python manage.py start_listener
    volumes:
      - ./project_video_hosting/:/app
    env_file:
      - ./project_video_hosting/.env



