# Generated by Django 5.2 on 2025-05-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='HostingUser',
        ),
    ]
