# Generated by Django 5.2 on 2025-05-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_rename_user_hostinguser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostingUser',
            new_name='User',
        ),
    ]
